"""
main.py — FastAPI application entry point for the graphology AI agent.

Exposes endpoints:
  POST /analyze   — accepts a handwriting image, runs the full graphology
                    pipeline, and returns a structured GraphologyReport.
  GET  /history   — returns last 10 analyses for the authenticated user.
  GET  /health    — lightweight liveness check.

Run locally with:
  uvicorn main:app --reload --port 8000
"""

import sys
import os
import asyncio

# Must be the very first thing — adds project root to sys.path before
# any submodule imports so that config, models, rule_engine are all found
# correctly by uvicorn worker processes on Windows
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import logging

from contextlib import asynccontextmanager
from appointments.router import router as appointments_router
from fastapi import FastAPI, File, HTTPException, UploadFile, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session

from agent.agent import run_graphology_pipeline
from models import GraphologyReport

# --- Auth & Database imports ---
from auth.router import router as auth_router
from auth.dependencies import get_current_user
from database import SqliteBase, sqlite_engine, get_db, User, Analysis

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lifespan — startup / shutdown events
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    SqliteBase.metadata.create_all(bind=sqlite_engine)
    logger.info("Database tables initialised.")

    print()
    print("=" * 60)
    print("  🖊️  Graphology AI Agent API is live")
    print("  Endpoints:")
    print("    POST /analyze   — submit a handwriting image")
    print("    GET  /history   — fetch past analyses")
    print("    GET  /health    — liveness check")
    print("=" * 60)
    print()
    logger.info("Graphology API started successfully.")
    yield
    logger.info("Graphology API shutting down.")

# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Graphology AI Agent",
    description=(
        "Upload a handwriting image and receive a personality analysis report "
        "generated by a multi-step Agno + Gemini pipeline."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# ---------------------------------------------------------------------------
# CORS middleware
# ---------------------------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://graphology.ulwerealestate.com",
        "https://graphology-0705.onrender.com",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

# Mount the auth router — exposes /auth/google, /auth/github, /auth/me, etc.
app.include_router(auth_router)
app.include_router(appointments_router)

# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/health", summary="Liveness check")
async def health() -> dict:
    """Return a simple OK status to confirm the service is running."""
    return {"status": "ok"}


@app.post(
    "/api/analyze",
    response_model=GraphologyReport,
    summary="Analyze handwriting image",
    response_description="Structured graphology report with personality traits.",
)
async def analyze(
    file: UploadFile = File(..., description="Handwriting image to analyze"),
    current_user: User = Depends(get_current_user),   # 🔒 Protected — requires valid JWT
    db: Session = Depends(get_db),
) -> GraphologyReport:
    """
    Accept a handwriting image upload, run the full graphology pipeline, and
    return a GraphologyReport containing personality traits and a disclaimer.

    Requires authentication — include a valid JWT in the Authorization header:
      Authorization: Bearer <your_token>

    - **file**: JPEG or PNG handwriting image (multipart/form-data, field name `file`).
    """
    logger.info(
        "POST /analyze — user_id=%d, file: '%s' (%s)",
        current_user.id,
        file.filename,
        file.content_type,
    )

    # -- Validate file type --
    allowed_types = {"image/jpeg", "image/png", "image/webp"}
    if file.content_type not in allowed_types:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type: {file.content_type}. Please upload a JPEG or PNG image.",
        )

    # -- Read uploaded bytes --
    try:
        image_bytes: bytes = await file.read()
        logger.info("File read successfully — %d bytes.", len(image_bytes))
    except Exception as exc:
        logger.error("Failed to read uploaded file: %s", exc)
        raise HTTPException(
            status_code=400,
            detail=f"Could not read the uploaded file: {exc}",
        ) from exc

    # -- Validate file size (max 10MB) --
    max_size = 10 * 1024 * 1024  # 10MB in bytes
    if len(image_bytes) > max_size:
        raise HTTPException(
            status_code=400,
            detail="File too large. Maximum allowed size is 10MB.",
        )

    # -- Run graphology pipeline --
    try:
        logger.info("Handing off to run_graphology_pipeline.")
        report: GraphologyReport = await asyncio.wait_for(
            run_graphology_pipeline(image_bytes),
            timeout=540,  # 9 minutes
        )
        logger.info("Pipeline completed — returning GraphologyReport.")

    except asyncio.TimeoutError:
        logger.error("Pipeline timed out after 540 seconds.")
        raise HTTPException(
            status_code=504,
            detail="The analysis took too long to complete. Please try again.",
        )

    except RuntimeError as exc:
        logger.error("Pipeline RuntimeError: %s", exc)
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        logger.exception("Unexpected error during pipeline execution: %s", exc)
        raise HTTPException(
            status_code=500,
            detail=(
                "An unexpected error occurred while processing the image. "
                "Please try again or contact support."
            ),
        ) from exc

    # -- Persist analysis to database --
    # Non-fatal — if DB save fails the user still gets their report
    try:
        analysis_record = Analysis(
            user_id=current_user.id,
            personality_traits=report.personality_traits,
            disclaimer=report.disclaimer,
        )
        db.add(analysis_record)
        db.commit()
        logger.info(
            "Analysis saved to DB — analysis_id=%d user_id=%d.",
            analysis_record.id,
            current_user.id,
        )
    except Exception as exc:
        logger.error("Failed to save analysis to DB: %s", exc)
        db.rollback()

    return report


@app.get(
    "/api/history",
    summary="Get analysis history for the current user",
)
async def get_history(
    current_user: User = Depends(get_current_user),   # 🔒 Protected
    db: Session = Depends(get_db),
) -> list:
    """
    Return the last 10 graphology analyses for the authenticated user,
    ordered by most recent first.

    Requires authentication — include a valid JWT in the Authorization header.
    """
    analyses = (
        db.query(Analysis)
        .filter(Analysis.user_id == current_user.id)
        .order_by(Analysis.created_at.desc())
        .limit(10)
        .all()
    )

    logger.info(
        "GET /history — user_id=%d, returning %d analyses.",
        current_user.id,
        len(analyses),
    )

    return [
        {
            "id": a.id,
            "personality_traits": a.personality_traits,
            "disclaimer": a.disclaimer,
            "created_at": a.created_at.isoformat(),
        }
        for a in analyses
    ]
